### ISSUE TITLE
make full is failing

### ISSUE THREAD

**Issue by veerendra2** [otsuarez/mkdocs_auth#2]
When I run `make full`
```
ubuntu@test-server:~/mkdocs_auth$ make full
rm -fr site/
mkdir site
mkdocs build --clean
WARNING -  Config value: 'theme_dir'. Warning: The configuration option {0} has been deprecated and will be removed in a future release of MkDocs. 
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /home/ubuntu/mkdocs_auth/site 
ERROR   -  Error building page index.md 
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/mkdocs/__main__.py", line 156, in build_command
    ), dirty=not clean)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/mkdocs/commands/build.py", line 282, in build
    build_pages(config, dirty=dirty)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/mkdocs/commands/build.py", line 242, in build_pages
    _build_page(page, config, site_navigation, env)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/mkdocs/commands/build.py", line 158, in _build_page
    output_content = template.render(context)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/mkdocs/themes/readthedocs/main.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/ubuntu/mkdocs_auth/theme_addons/base.html", line 82, in top-level template code
    <li>{% include "toc.html" %}<li>
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/mkdocs/themes/readthedocs/toc.html", line 2, in top-level template code
    <li class="toctree-l{{ navlevel + 1 }}"><a href="{{ toc_item.url }}">{{ toc_item.title }}</a></li>
jinja2.exceptions.UndefinedError: 'navlevel' is undefined
make: *** [build] Error 1

```

**Comment by otsuarez** [comment]
Hi, I noticed you're using python3. Let me run some tests, I'll update the ticket as soon as possible. Thanks for raising the issue.

**Comment by anitavincent** [comment]
Same with python2.7

**Comment by otsuarez** [comment]
got it, i'll take a look later tonight and will try to push a working version for tomorrow.

**Comment by otsuarez** [comment]
Hi, 
I updated the scripts, added a `requirements.txt` to prevent newer versions of `mkdocs` from breaking this repo without notice.
I'm updating now the README file with a set of instructions to run the code, check the `using a container` section.
